package org.canbadia.commerce;

import org.bukkit.Material;
import org.canbadia.Product;

import java.util.HashMap;
import java.util.Map;

/**
 * Author: Marc Badia Cendros (randolph)
 * Date: 05/02/12
 * Time: 18:01
 * Mail: marc.badiac@gmail.com
 */
public abstract class MarketMaterials {
    private static Map<Material, Product> products;
    private static final int MIN_PRICE = 52;
    private static final int MAX_PRICE = 455;
    private static final int MIN_QUANTITY = 15;
    private static final int MAX_QUANTITY = 64;
    private static final int QUANTITY = 40;

    /**
     * Generate the Map of the products for the market
     *
     * @return Map<Material, Product>
     */
    public static Map<Material, Product> generateProducts() {
        products = new HashMap<Material, Product>();
        //products.put(Material.AIR, new Product(Material.AIR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE, new Product(Material.STONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        //products.put(Material.GRASS, new Product(Material.GRASS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIRT, new Product(Material.DIRT, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COBBLESTONE, new Product(Material.COBBLESTONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD, new Product(Material.WOOD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SAPLING, new Product(Material.SAPLING, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BEDROCK, new Product(Material.BEDROCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WATER, new Product(Material.WATER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STATIONARY_WATER, new Product(Material.STATIONARY_WATER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LAVA, new Product(Material.LAVA, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STATIONARY_LAVA, new Product(Material.STATIONARY_LAVA, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SAND, new Product(Material.SAND, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GRAVEL, new Product(Material.GRAVEL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_ORE, new Product(Material.GOLD_ORE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_ORE, new Product(Material.IRON_ORE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COAL_ORE, new Product(Material.COAL_ORE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LOG, new Product(Material.LOG, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LEAVES, new Product(Material.LEAVES, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SPONGE, new Product(Material.SPONGE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GLASS, new Product(Material.GLASS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LAPIS_ORE, new Product(Material.LAPIS_ORE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LAPIS_BLOCK, new Product(Material.LAPIS_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DISPENSER, new Product(Material.DISPENSER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SANDSTONE, new Product(Material.SANDSTONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.NOTE_BLOCK, new Product(Material.NOTE_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BED_BLOCK, new Product(Material.BED_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.POWERED_RAIL, new Product(Material.POWERED_RAIL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DETECTOR_RAIL, new Product(Material.DETECTOR_RAIL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PISTON_STICKY_BASE, new Product(Material.PISTON_STICKY_BASE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WEB, new Product(Material.WEB, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LONG_GRASS, new Product(Material.LONG_GRASS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DEAD_BUSH, new Product(Material.DEAD_BUSH, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PISTON_BASE, new Product(Material.PISTON_BASE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PISTON_EXTENSION, new Product(Material.PISTON_EXTENSION, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOL, new Product(Material.WOOL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PISTON_MOVING_PIECE, new Product(Material.PISTON_MOVING_PIECE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.YELLOW_FLOWER, new Product(Material.YELLOW_FLOWER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
//        products.put(Material.RED_ROSE, new Product(Material.RED_ROSE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BROWN_MUSHROOM, new Product(Material.BROWN_MUSHROOM, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RED_MUSHROOM, new Product(Material.RED_MUSHROOM, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_BLOCK, new Product(Material.GOLD_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_BLOCK, new Product(Material.IRON_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DOUBLE_STEP, new Product(Material.DOUBLE_STEP, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STEP, new Product(Material.STEP, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BRICK, new Product(Material.BRICK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.TNT, new Product(Material.TNT, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BOOKSHELF, new Product(Material.BOOKSHELF, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MOSSY_COBBLESTONE, new Product(Material.MOSSY_COBBLESTONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.OBSIDIAN, new Product(Material.OBSIDIAN, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.TORCH, new Product(Material.TORCH, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FIRE, new Product(Material.FIRE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MOB_SPAWNER, new Product(Material.MOB_SPAWNER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_STAIRS, new Product(Material.WOOD_STAIRS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CHEST, new Product(Material.CHEST, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.REDSTONE_WIRE, new Product(Material.REDSTONE_WIRE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_ORE, new Product(Material.DIAMOND_ORE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_BLOCK, new Product(Material.DIAMOND_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WORKBENCH, new Product(Material.WORKBENCH, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CROPS, new Product(Material.CROPS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SOIL, new Product(Material.SOIL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FURNACE, new Product(Material.FURNACE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BURNING_FURNACE, new Product(Material.BURNING_FURNACE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SIGN_POST, new Product(Material.SIGN_POST, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOODEN_DOOR, new Product(Material.WOODEN_DOOR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LADDER, new Product(Material.LADDER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RAILS, new Product(Material.RAILS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COBBLESTONE_STAIRS, new Product(Material.COBBLESTONE_STAIRS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WALL_SIGN, new Product(Material.WALL_SIGN, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LEVER, new Product(Material.LEVER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE_PLATE, new Product(Material.STONE_PLATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_DOOR_BLOCK, new Product(Material.IRON_DOOR_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_PLATE, new Product(Material.WOOD_PLATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.REDSTONE_ORE, new Product(Material.REDSTONE_ORE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GLOWING_REDSTONE_ORE, new Product(Material.GLOWING_REDSTONE_ORE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.REDSTONE_TORCH_OFF, new Product(Material.REDSTONE_TORCH_OFF, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.REDSTONE_TORCH_ON, new Product(Material.REDSTONE_TORCH_ON, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE_BUTTON, new Product(Material.STONE_BUTTON, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
//        products.put(Material.SNOW, new Product(Material.SNOW, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
//        products.put(Material.ICE, new Product(Material.ICE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
//        products.put(Material.SNOW_BLOCK, new Product(Material.SNOW_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CACTUS, new Product(Material.CACTUS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CLAY, new Product(Material.CLAY, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SUGAR_CANE_BLOCK, new Product(Material.SUGAR_CANE_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.JUKEBOX, new Product(Material.JUKEBOX, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FENCE, new Product(Material.FENCE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PUMPKIN, new Product(Material.PUMPKIN, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.NETHERRACK, new Product(Material.NETHERRACK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SOUL_SAND, new Product(Material.SOUL_SAND, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GLOWSTONE, new Product(Material.GLOWSTONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PORTAL, new Product(Material.PORTAL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.JACK_O_LANTERN, new Product(Material.JACK_O_LANTERN, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CAKE_BLOCK, new Product(Material.CAKE_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIODE_BLOCK_OFF, new Product(Material.DIODE_BLOCK_OFF, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIODE_BLOCK_ON, new Product(Material.DIODE_BLOCK_ON, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LOCKED_CHEST, new Product(Material.LOCKED_CHEST, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.TRAP_DOOR, new Product(Material.TRAP_DOOR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MONSTER_EGGS, new Product(Material.MONSTER_EGGS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SMOOTH_BRICK, new Product(Material.SMOOTH_BRICK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.HUGE_MUSHROOM_1, new Product(Material.HUGE_MUSHROOM_1, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.HUGE_MUSHROOM_2, new Product(Material.HUGE_MUSHROOM_2, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_FENCE, new Product(Material.IRON_FENCE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.THIN_GLASS, new Product(Material.THIN_GLASS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MELON_BLOCK, new Product(Material.MELON_BLOCK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PUMPKIN_STEM, new Product(Material.PUMPKIN_STEM, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MELON_STEM, new Product(Material.MELON_STEM, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.VINE, new Product(Material.VINE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FENCE_GATE, new Product(Material.FENCE_GATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BRICK_STAIRS, new Product(Material.BRICK_STAIRS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SMOOTH_STAIRS, new Product(Material.SMOOTH_STAIRS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MYCEL, new Product(Material.MYCEL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WATER_LILY, new Product(Material.WATER_LILY, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.NETHER_BRICK, new Product(Material.NETHER_BRICK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.NETHER_FENCE, new Product(Material.NETHER_FENCE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.NETHER_BRICK_STAIRS, new Product(Material.NETHER_BRICK_STAIRS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.NETHER_WARTS, new Product(Material.NETHER_WARTS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.ENCHANTMENT_TABLE, new Product(Material.ENCHANTMENT_TABLE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BREWING_STAND, new Product(Material.BREWING_STAND, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CAULDRON, new Product(Material.CAULDRON, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.ENDER_PORTAL, new Product(Material.ENDER_PORTAL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.ENDER_PORTAL_FRAME, new Product(Material.ENDER_PORTAL_FRAME, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.ENDER_STONE, new Product(Material.ENDER_STONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DRAGON_EGG, new Product(Material.DRAGON_EGG, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        // ----- Item Separator --, MIN_PRICE,  MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY---
        products.put(Material.IRON_SPADE, new Product(Material.IRON_SPADE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_PICKAXE, new Product(Material.IRON_PICKAXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_AXE, new Product(Material.IRON_AXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FLINT_AND_STEEL, new Product(Material.FLINT_AND_STEEL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.APPLE, new Product(Material.APPLE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BOW, new Product(Material.BOW, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.ARROW, new Product(Material.ARROW, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COAL, new Product(Material.COAL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND, new Product(Material.DIAMOND, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_INGOT, new Product(Material.IRON_INGOT, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_INGOT, new Product(Material.GOLD_INGOT, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_SWORD, new Product(Material.IRON_SWORD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_SWORD, new Product(Material.WOOD_SWORD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_SPADE, new Product(Material.WOOD_SPADE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_PICKAXE, new Product(Material.WOOD_PICKAXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_AXE, new Product(Material.WOOD_AXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE_SWORD, new Product(Material.STONE_SWORD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE_SPADE, new Product(Material.STONE_SPADE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE_PICKAXE, new Product(Material.STONE_PICKAXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE_AXE, new Product(Material.STONE_AXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_SWORD, new Product(Material.DIAMOND_SWORD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_SPADE, new Product(Material.DIAMOND_SPADE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_PICKAXE, new Product(Material.DIAMOND_PICKAXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_AXE, new Product(Material.DIAMOND_AXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STICK, new Product(Material.STICK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BOWL, new Product(Material.BOWL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MUSHROOM_SOUP, new Product(Material.MUSHROOM_SOUP, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_SWORD, new Product(Material.GOLD_SWORD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_SPADE, new Product(Material.GOLD_SPADE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_PICKAXE, new Product(Material.GOLD_PICKAXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_AXE, new Product(Material.GOLD_AXE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STRING, new Product(Material.STRING, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FEATHER, new Product(Material.FEATHER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SULPHUR, new Product(Material.SULPHUR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_HOE, new Product(Material.WOOD_HOE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STONE_HOE, new Product(Material.STONE_HOE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_HOE, new Product(Material.IRON_HOE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_HOE, new Product(Material.DIAMOND_HOE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_HOE, new Product(Material.GOLD_HOE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SEEDS, new Product(Material.SEEDS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WHEAT, new Product(Material.WHEAT, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BREAD, new Product(Material.BREAD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LEATHER_HELMET, new Product(Material.LEATHER_HELMET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LEATHER_CHESTPLATE, new Product(Material.LEATHER_CHESTPLATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LEATHER_LEGGINGS, new Product(Material.LEATHER_LEGGINGS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LEATHER_BOOTS, new Product(Material.LEATHER_BOOTS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CHAINMAIL_HELMET, new Product(Material.CHAINMAIL_HELMET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CHAINMAIL_CHESTPLATE, new Product(Material.CHAINMAIL_CHESTPLATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CHAINMAIL_LEGGINGS, new Product(Material.CHAINMAIL_LEGGINGS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CHAINMAIL_BOOTS, new Product(Material.CHAINMAIL_BOOTS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_HELMET, new Product(Material.IRON_HELMET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_CHESTPLATE, new Product(Material.IRON_CHESTPLATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_LEGGINGS, new Product(Material.IRON_LEGGINGS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_BOOTS, new Product(Material.IRON_BOOTS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_HELMET, new Product(Material.DIAMOND_HELMET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_CHESTPLATE, new Product(Material.DIAMOND_CHESTPLATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_LEGGINGS, new Product(Material.DIAMOND_LEGGINGS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIAMOND_BOOTS, new Product(Material.DIAMOND_BOOTS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_HELMET, new Product(Material.GOLD_HELMET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_CHESTPLATE, new Product(Material.GOLD_CHESTPLATE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_LEGGINGS, new Product(Material.GOLD_LEGGINGS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_BOOTS, new Product(Material.GOLD_BOOTS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FLINT, new Product(Material.FLINT, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PORK, new Product(Material.PORK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GRILLED_PORK, new Product(Material.GRILLED_PORK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PAINTING, new Product(Material.PAINTING, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLDEN_APPLE, new Product(Material.GOLDEN_APPLE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SIGN, new Product(Material.SIGN, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WOOD_DOOR, new Product(Material.WOOD_DOOR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BUCKET, new Product(Material.BUCKET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WATER_BUCKET, new Product(Material.WATER_BUCKET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LAVA_BUCKET, new Product(Material.LAVA_BUCKET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MINECART, new Product(Material.MINECART, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SADDLE, new Product(Material.SADDLE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.IRON_DOOR, new Product(Material.IRON_DOOR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.REDSTONE, new Product(Material.REDSTONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SNOW_BALL, new Product(Material.SNOW_BALL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BOAT, new Product(Material.BOAT, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.LEATHER, new Product(Material.LEATHER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MILK_BUCKET, new Product(Material.MILK_BUCKET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CLAY_BRICK, new Product(Material.CLAY_BRICK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CLAY_BALL, new Product(Material.CLAY_BALL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SUGAR_CANE, new Product(Material.SUGAR_CANE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PAPER, new Product(Material.PAPER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BOOK, new Product(Material.BOOK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SLIME_BALL, new Product(Material.SLIME_BALL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.STORAGE_MINECART, new Product(Material.STORAGE_MINECART, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.POWERED_MINECART, new Product(Material.POWERED_MINECART, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.EGG, new Product(Material.EGG, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COMPASS, new Product(Material.COMPASS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FISHING_ROD, new Product(Material.FISHING_ROD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.WATCH, new Product(Material.WATCH, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GLOWSTONE_DUST, new Product(Material.GLOWSTONE_DUST, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RAW_FISH, new Product(Material.RAW_FISH, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COOKED_FISH, new Product(Material.COOKED_FISH, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.INK_SACK, new Product(Material.INK_SACK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BONE, new Product(Material.BONE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SUGAR, new Product(Material.SUGAR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CAKE, new Product(Material.CAKE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BED, new Product(Material.BED, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.DIODE, new Product(Material.DIODE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COOKIE, new Product(Material.COOKIE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MAP, new Product(Material.MAP, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SHEARS, new Product(Material.SHEARS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MELON, new Product(Material.MELON, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.PUMPKIN_SEEDS, new Product(Material.PUMPKIN_SEEDS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MELON_SEEDS, new Product(Material.MELON_SEEDS, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RAW_BEEF, new Product(Material.RAW_BEEF, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COOKED_BEEF, new Product(Material.COOKED_BEEF, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RAW_CHICKEN, new Product(Material.RAW_CHICKEN, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.COOKED_CHICKEN, new Product(Material.COOKED_CHICKEN, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.ROTTEN_FLESH, new Product(Material.ROTTEN_FLESH, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.ENDER_PEARL, new Product(Material.ENDER_PEARL, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BLAZE_ROD, new Product(Material.BLAZE_ROD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GHAST_TEAR, new Product(Material.GHAST_TEAR, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_NUGGET, new Product(Material.GOLD_NUGGET, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.NETHER_STALK, new Product(Material.NETHER_STALK, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.POTION, new Product(Material.POTION, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GLASS_BOTTLE, new Product(Material.GLASS_BOTTLE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SPIDER_EYE, new Product(Material.SPIDER_EYE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.FERMENTED_SPIDER_EYE, new Product(Material.FERMENTED_SPIDER_EYE, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BLAZE_POWDER, new Product(Material.BLAZE_POWDER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MAGMA_CREAM, new Product(Material.MAGMA_CREAM, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.BREWING_STAND_ITEM, new Product(Material.BREWING_STAND_ITEM, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.CAULDRON_ITEM, new Product(Material.CAULDRON_ITEM, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.EYE_OF_ENDER, new Product(Material.EYE_OF_ENDER, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.SPECKLED_MELON, new Product(Material.SPECKLED_MELON, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.MONSTER_EGG, new Product(Material.MONSTER_EGG, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GOLD_RECORD, new Product(Material.GOLD_RECORD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.GREEN_RECORD, new Product(Material.GREEN_RECORD, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_3, new Product(Material.RECORD_3, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_4, new Product(Material.RECORD_4, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_5, new Product(Material.RECORD_5, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_6, new Product(Material.RECORD_6, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_7, new Product(Material.RECORD_7, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_8, new Product(Material.RECORD_8, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_9, new Product(Material.RECORD_9, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_10, new Product(Material.RECORD_10, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));
        products.put(Material.RECORD_11, new Product(Material.RECORD_11, MIN_PRICE, MAX_PRICE, MIN_QUANTITY, MAX_QUANTITY, QUANTITY));

        return products;
    }
}
